### ISSUE TITLE
The plugin does not do a thing

### ISSUE THREAD

**Issue by soullivaneuh** [constverum/stylelint-config-rational-order#22]
With this css:

```css
h1 {
  position: absolute;
  display: block;
  float: right;
  color: black;
  background-color: blue;
  border: 1px black solid;
}
```

This configuration (basically copy/pasta).

```
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-rational-order"
  ],
  "plugins": [
    "stylelint-order",
    "stylelint-config-rational-order/plugin"
  ],
  "rules": {
    "order/properties-order": [],
    "plugin/rational-order": [true, {
      "border-in-box-model": false,
      "empty-line-between-groups": true,
    }]
  }
}
```

And the command:

```
stylelint --config config/.stylelintrc --fix fixtures/main.css
```

Strictly nothing happen.
